-- MySQL Script generated by MySQL Workbench
-- Mon May 25 12:08:30 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_libreria` DEFAULT CHARACTER SET utf8 ;
USE `sistema_libreria` ;

-- -----------------------------------------------------
-- Table `sistema_libreria`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_libreria`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NULL,
  `descripcion_rol` VARCHAR(200) NULL,
  `created_at` DATETIME NULL, -- Fecha de creacion
  `update_at` DATETIME NULL, -- Fecha de actualizacion
  `created_by` INT NULL,
  `deleted` TINYINT(1) NULL, -- Borrado logico
  -- deleted 0 activo, deleted 1 oculto
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `id_rol_UNIQUE` (`id_rol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_libreria`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_libreria`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL, -- Fecha de creacion
  `update_at` DATETIME NULL, -- Fecha de actualizacion
  `created_by` INT NULL,
  `deleted` TINYINT(1) NULL, -- Borrado logico
  -- deleted 0 activo, deleted 1 oculto 
  `roles_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuarios_UNIQUE` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  INDEX `fk_Usuario_roles1_idx` (`roles_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_roles1`
    FOREIGN KEY (`roles_id_rol`)
    REFERENCES `sistema_libreria`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_libreria`.`Autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_libreria`.`Autores` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre_autor` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_autor`),
  UNIQUE INDEX `id_autor_UNIQUE` (`id_autor` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_libreria`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_libreria`.`Libro` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `id_autor` INT NOT NULL,
  `disponible` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_libro`),
  UNIQUE INDEX `id_libro_UNIQUE` (`id_libro` ASC) VISIBLE,
  INDEX `fk_Libro_Autores1_idx` (`id_autor` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_Autores1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `sistema_libreria`.`Autores` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_libreria`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_libreria`.`Prestamo` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `update_at` DATETIME NULL, -- Fecha de actualizacion
  `created_at` DATETIME NULL, -- Fecha de creacion
  `created_by` INT NULL,
  `id_libro` INT NOT NULL,
  `id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  UNIQUE INDEX `id_prestamo_UNIQUE` (`id_prestamo` ASC) VISIBLE,
  INDEX `fk_Prestamo_Libro_idx` (`id_libro` ASC) VISIBLE,
  INDEX `fk_Prestamo_Usuario1_idx` (`id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamo_Libro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `sistema_libreria`.`Libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Usuario1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `sistema_libreria`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE sistema_libreria;

-- INGRESAR ROLES
INSERT INTO roles(nombre_rol, descripcion_rol, created_at, created_by, deleted)
VALUES ("administrador", "Control total del sistema", NOW(), 1, 0),
("bibliotecario", "Puede gestionar libros y prestamos", NOW(), 1, 0),
("lector", "Puede solicitar libros prestados", NOW(), 1, 0);

-- MOSTRAR ROLES
SELECT * FROM roles;

-- INGRESAR USUARIOS
INSERT INTO Usuario(nombre, correo, created_by, deleted, roles_id_rol)
VALUES ("Camila Torres", "camila@correo.com", 1, 0, 3),
("Claudia Pina", "claudia@correo.com", 1, 0, 3),
("Ana Perez", "ana@correo.com", 1, 0, 2);

-- MOSTRAR USUARIOS
SELECT * FROM Usuario;

-- INGRESAR AUTORES
INSERT INTO Autores(nombre_autor, correo)
VALUES ("Ana Perez", "ana.autor@correo.com"),
("Joshua Cortejo", "joshua.autor@correo.com"),
("Carlos Rojas", "carlos.autor@correo.com");

-- MOSTRAR AUTORES
SELECT * FROM Autores;

-- INGRESAR LIBROS
INSERT INTO Libro(titulo, id_autor, disponible)
VALUES ("Python desde cero", 1, 1),
("Humpty Dumpty", 2, 1),
("Base de datos inicial", 3, 1);

-- MOSTRAR LIBROS
SELECT id_libro, titulo, id_autor, disponible
FROM Libro;

-- INGRESAR PRESTAMOS
INSERT INTO Prestamo(created_by, id_libro, id_usuarios)
VALUES (2, 1, 1),
(2, 2, 2);

-- MOSTRAR PRESTAMOS
SELECT * FROM Prestamo;

-- CONSULTAS SIMPLES CON CONDICION
-- WHERE aplica la condicion sobre la consulta
-- MOSTRAR USUARIOS ACTIVOS
SELECT nombre, correo, roles_id_rol, deleted
FROM Usuario
WHERE deleted = 0;

-- MOSTRAR LIBROS DISPONIBLES
SELECT id_libro, titulo, id_autor, disponible
FROM Libro
WHERE disponible = 1;

-- CAMBIAR DISPONIBILIDAD DE UN LIBRO
UPDATE Libro
SET disponible = 0
WHERE id_libro = 1;

-- MOSTRAR LIBROS
SELECT id_libro, titulo, id_autor, disponible
FROM Libro;

-- BORRADO LOGICO DE UN USUARIO
UPDATE Usuario
SET deleted = 1
WHERE id_usuario = 2;

-- MOSTRAR USUARIOS
SELECT nombre, correo, deleted
FROM Usuario;

-- RECUPERAR USUARIO
UPDATE Usuario
SET deleted = 0
WHERE id_usuario = 2;

-- VER SOLO ACTIVOS
SELECT nombre, correo, deleted
FROM Usuario
WHERE deleted = 0;

-- VER ROLES ACTIVOS
SELECT id_rol, nombre_rol, descripcion_rol, deleted
FROM roles
WHERE deleted = 0;

-- VER LIBROS DISPONIBLES
SELECT id_libro, titulo, id_autor, disponible
FROM Libro
WHERE disponible = 1;
